# Generated by Django 3.2.3 on 2021-09-09 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(choices=[('30min', '30 Minutes Per Month'), ('1hour', '1 Hour Per Month'), ('2hour', '2 Hours Per Month'), ('4hour', '4 Hours Per Month')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_address', models.CharField(blank=True, max_length=200, null=True)),
                ('client_registered_company_number', models.CharField(blank=True, max_length=30, null=True)),
                ('live_client', models.BooleanField(default=True)),
                ('date_registered', models.DateTimeField(verbose_name='Date Registered')),
                ('contract_start_date', models.DateTimeField()),
                ('contracted_monthly_service_hours', models.FloatField(default=2)),
                ('contracted_monthly_SEM_hours', models.FloatField(default=2)),
                ('paid_extra_hours', models.FloatField(default=0)),
                ('hours_used_this_month', models.FloatField(default=0)),
                ('discontented_client', models.BooleanField(default=False)),
                ('priority_client', models.BooleanField(default=False)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.contract')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
