# Generated by Django 3.2.3 on 2021-06-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('live_client', models.BooleanField(default=True)),
                ('date_registered', models.DateTimeField(verbose_name='Date Registered')),
                ('contract_start_date', models.DateTimeField()),
                ('contracted_monthly_service_hours', models.FloatField(default=1)),
                ('contracted_monthly_SEM_hours', models.FloatField(default=0)),
                ('paid_extra_hours', models.FloatField(default=0)),
                ('hours_used_this_month', models.FloatField(default=0)),
                ('discontented_client', models.BooleanField(default=False)),
                ('priority_client', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(choices=[('30min', '30 Minutes Per Month'), ('1hour', '1 Hour Per Month'), ('2hour', '2 Hours Per Month'), ('4hour', '4 Hours Per Month'), ('other', 'Bespoke')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrike_api_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('wrike_number', models.CharField(max_length=10)),
                ('severity', models.CharField(choices=[('ST', 'Standard'), ('HI', 'High'), ('VH', 'Very High'), ('CR', 'Critical')], max_length=2)),
                ('hours_predicted', models.FloatField(default=0)),
                ('hours_used', models.FloatField(default=0)),
                ('customer_feedback_requested', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('file_upload', models.FileField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.client')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_information', models.TextField()),
                ('date_sent', models.DateTimeField(verbose_name='Date Sent')),
                ('client_responded', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.contract'),
        ),
    ]
