# Generated by Django 3.2.3 on 2021-09-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrike_api_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('issue', models.TextField()),
                ('wrike_number', models.CharField(max_length=10)),
                ('severity', models.CharField(choices=[('ST', 'Standard'), ('HI', 'High'), ('VH', 'Very High'), ('CR', 'Critical')], max_length=2)),
                ('hours_predicted', models.FloatField(default=0)),
                ('hours_used', models.FloatField(default=0)),
                ('customer_feedback_requested', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(null=True, verbose_name='Date Updated')),
                ('file_upload', models.FileField(null=True, upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_sent', models.DateTimeField(blank=True, verbose_name='Date Sent')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
