# Generated by Django 3.2.3 on 2021-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
