# Generated by Django 3.2.3 on 2021-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210718_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(choices=[('30min', '30 Minutes Per Month'), ('1hour', '1 Hour Per Month'), ('2hour', '2 Hours Per Month'), ('4hour', '4 Hours Per Month')], max_length=5),
        ),
    ]
