# Generated by Django 3.2.3 on 2021-07-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_contract_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.client'),
        ),
    ]
