# Generated by Django 3.2.3 on 2021-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20210725_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contracted_monthly_service_hours',
            field=models.FloatField(default=2),
        ),
    ]
